// Videns' geometry against Python geographiclib (tests/vectors/geodesic.json, generated by
// tools/vectors/make_vectors.py). The expectations come from a different implementation
// in a different language, so a shared mistake cannot pass both (VIDENS_SPEC.md 10).

import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { ellipseRing } from "../src/geo/ellipse.ts";
import { geodesicDirect, geodesicInverse } from "../src/geo/geodesic.ts";
import { geodesicLine } from "../src/geo/lines.ts";

interface Vectors {
  direct: { from: string; lat1: number; lon1: number; azi1: number; s12: number; lat2: number; lon2: number }[];
  inverse: { from: string; to: string; lat1: number; lon1: number; lat2: number; lon2: number; s12: number; azi1: number }[];
  ellipses: { at: string; lat: number; lon: number; semi_major_m: number; semi_minor_m: number; orientation_deg: number; vertices: number; ring: [number, number][] }[];
  lines: { from: string; lat: number; lon: number; azimuth_deg: number; length_m: number; points: [number, number][] }[];
}

const vectors = JSON.parse(readFileSync(join(import.meta.dirname, "vectors", "geodesic.json"), "utf8")) as Vectors;

/** Ground distance between two [lon, lat] points, metres. */
const apart = (a: [number, number], b: [number, number]) => geodesicInverse(a[1], a[0], b[1], b[0]).distanceM;

describe("against Python geographiclib", () => {
  it("has vectors at the origin, far from it, at high latitude and across the antimeridian", () => {
    const places = new Set(vectors.ellipses.map((e) => e.at));
    for (const p of ["neutral_origin", "50km_north", "60N", "antimeridian", "southern"]) expect(places).toContain(p);
  });

  it("solves the direct problem to within a millimetre", () => {
    for (const v of vectors.direct) {
      const p = geodesicDirect(v.lat1, v.lon1, v.azi1, v.s12);
      expect(apart([p.lon, p.lat], [v.lon2, v.lat2]), `${v.from} ${v.azi1} ${v.s12}`).toBeLessThan(0.001);
      expect(p.lon).toBeCloseTo(v.lon2, 9); // unrolled across the antimeridian, not wrapped
    }
  });

  it("solves the inverse problem: distance to a millimetre, azimuth to a microdegree", () => {
    for (const v of vectors.inverse) {
      const r = geodesicInverse(v.lat1, v.lon1, v.lat2, v.lon2);
      expect(Math.abs(r.distanceM - v.s12), `${v.from}->${v.to}`).toBeLessThan(0.001);
      expect(Math.abs(((r.azimuthDeg - v.azi1 + 540) % 360) - 180)).toBeLessThan(1e-6);
    }
  });

  it("traces every ellipse vertex to within a millimetre", () => {
    for (const e of vectors.ellipses) {
      const ring = ellipseRing(e.lat, e.lon, { semiMajorM: e.semi_major_m, semiMinorM: e.semi_minor_m, orientationDeg: e.orientation_deg, confidence: 0.95 }, e.vertices);
      e.ring.forEach((expected, i) => {
        expect(apart(ring[i]!, expected), `${e.at} ${e.semi_major_m}x${e.semi_minor_m}@${e.orientation_deg} vertex ${i}`).toBeLessThan(0.001);
      });
    }
  });

  it("draws a 50 km line of bearing within 1 m of the geodesic at every sample (Phase 3 gate)", () => {
    for (const l of vectors.lines) {
      const line = geodesicLine(l.lat, l.lon, l.azimuth_deg, l.length_m, l.points.length - 1);
      l.points.forEach((expected, i) => expect(apart(line[i]!, expected), `${l.from} ${l.azimuth_deg} #${i}`).toBeLessThan(1));
    }
  });
});

describe("the tests would catch the rendering shortcut", () => {
  it("a straight line in Web Mercator misses the geodesic midpoint by far more than 1 m at 60 N", () => {
    const l = vectors.lines.find((x) => x.from === "60N" && x.azimuth_deg === 45)!;
    const [lon0, lat0] = l.points[0]!;
    const [lon1, lat1] = l.points.at(-1)!;
    const y = (lat: number) => Math.log(Math.tan(Math.PI / 4 + (lat * Math.PI) / 360));
    const lat = (yy: number) => (360 / Math.PI) * Math.atan(Math.exp(yy)) - 90;
    const mercatorMid: [number, number] = [(lon0 + lon1) / 2, lat((y(lat0) + y(lat1)) / 2)];
    const geodesicMid = l.points[8]!;
    expect(apart(mercatorMid, geodesicMid)).toBeGreaterThan(20);
  });
});
